{{- if eq .Values.operatorinstall_tempo "enabled" }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1" # 1=ns 2=sub 3=instance
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
  name: openshift-tempo-operator
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-tempo-operator
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1" # 1=ns 2=sub 3=instance
  labels:
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-product
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2" # 1=ns 2=sub 3=instance
  labels:
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
spec:
  channel: stable
  installPlanApproval: Automatic
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
---
{{- if and ( eq .Values.tempo_instance "enabled" ) ( eq .Values.after_subscription_install_run "enabled" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret-for-tempo
  labels:
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
stringData:
  endpoint: "https://{{ coalesce .Values.minio_endpoint "minio.apps.ocp4.jnyilimb.eu" }}"
  bucket: "{{ coalesce .Values.minio_bucket_tempo "tempo" }}"
  access_key_id: "{{ coalesce .Values.minio_username "minioadmin" }}"
  access_key_secret: {{ coalesce .Values.minio_password "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG" }}
---
# apiVersion: tempo.grafana.com/v1alpha1
# kind: TempoStack
# metadata:
#   name: tempo
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#     argocd.argoproj.io/sync-wave: "3" # 1=ns 2=sub 3=instance
# spec:
#   storageSize: 1Gi
#   storage: 
#     secret:
#       name: minio-secret-for-tempo
#       type: s3
#   resources:
#     total:
#       limits:
#         memory: 2Gi
#         cpu: 2000m
#   template:
#     queryFrontend:
#       jaegerQuery: 
#         enabled: true
#         monitorTab:
#           enabled: true 
#           prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
#         ingress:
#           route:
#             termination: edge
#           type: route
# ---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3" # 1=ns 2=sub 3=instance
  labels:
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
spec:
  storage:
    traces:
      backend: s3 
      size: 1Gi
      s3: 
        secret: minio-secret-for-tempo
    tls: 
      enabled: true
  jaegerui:
    enabled: true 
    route:
      enabled: true 
  resources: 
    limits:
      memory: 3Gi
      cpu: 2000m
{{- end }}