apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  minio.endpoint: "{{ coalesce .Values.minio_endpoint "minio.apps.ocp4.jnyilimb.eu" }}"
  minio.access-key: "{{ coalesce .Values.minio_username "minioadmin" }}"
  minio.secret-key: {{ coalesce .Values.minio_password "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG" }}
  minio.bucket.tempo: {{ coalesce .Values.minio_bucket_tempo "tempo" }}
  minio.bucket.usecase5: {{ coalesce .Values.minio_bucket_usecase5 "usecase5" }}
  minio.bucket.usecase7: {{ coalesce .Values.minio_bucket_usecase7 "usecase7" }}