{{- if eq .Values.operatorinstall_camelk "enabled" }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    olm.managed: "true"
    operators.coreos.com/red-hat-camel-k.openshift-operators: ""
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
  name: red-hat-camel-k
  namespace: openshift-operators
spec:
  channel: 1.10.x
  installPlanApproval: Automatic
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end}}