apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
stringData:
  db.host: {{ coalesce .Values.postgresql_database_host "postgres" }}
  db.name: {{ coalesce .Values.postgresql_database_name "transactions" }}
  db.user: {{ coalesce .Values.postgresql_user "postgres" }}
  db.password: {{ coalesce .Values.postgresql_password "P@ssw0rd" }}
  db.port: {{ coalesce .Values.postgresql_port "5432" | quote }}
  db.table: {{ coalesce .Values.postgresql_database_table "transactions" }}
---
{{ if eq .Values.postgresql_instance_cloudnativepg "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cnpg.io/operatorVersion: "1.23.3"
  labels:
    cnpg.io/cluster: {{ coalesce .Values.postgresql_database_host "postgres" }}
    cnpg.io/reload: "true"
  name: cloudnativepg-{{ coalesce .Values.postgresql_database_host "postgres" }}-secret
stringData:
  host: {{ coalesce .Values.postgresql_database_host "postgres" }}
  dbname: {{ coalesce .Values.postgresql_database_name "transactions" }}
  user: {{ coalesce .Values.postgresql_user "postgres" }}
  username: {{ coalesce .Values.postgresql_user "postgres" }}
  password: {{ coalesce .Values.postgresql_password "P@ssw0rd" }}
  port: {{ coalesce .Values.postgresql_port "5432" | quote }}
{{- end }}