{{- if eq .Values.operatorinstall_devspaces "enabled" }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    olm.managed: "true"
    operators.coreos.com/devworkspace-operator.openshift-operators: ""
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
  name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/devspaces.openshift-operators: ""
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
  name: devspaces
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
