{{- if and ( eq .Values.amqbroker_instance "enabled" ) ( eq .Values.after_subscription_install_run "enabled" ) }}
apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: broker-amq-mqtt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3" # 1=ns 2=sub 3=instance
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
    - expose: true
      name: mqtt
      port: {{ .Values.amqbroker_port }}
      protocols: mqtt
  adminPassword: {{ .Values.amqbroker_username }}
  adminUser: {{ .Values.amqbroker_password }}
  console:
    expose: true
  deploymentPlan:
    labels:
      app.kubernetes.io/part-of: camel-k-poc-infrastructure
    size: {{ coalesce .Values.amqbroker_replicas "1" }}
    messageMigration: false
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
  upgrades:
    enabled: false
    minor: false
{{- end }}
