apiVersion: v1
kind: Secret
metadata:
  name: mqtt-secret
  labels:
    app.kubernetes.io/part-of: camel-k-poc-infrastructure
stringData:
  broker.url: {{ include "infrastructure.amqbrokerurl" . }}
  broker.user: "{{ coalesce .Values.amqbroker_username "admin" }}"
  broker.password: "{{ coalesce .Values.amqbroker_password "admin" }}"