apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    che.eclipse.org/checluster-defaults-cleanup: '{"containers.resources":"true","spec.components.dashboard.headerMessage":"true","spec.components.pluginRegistry.openVSXURL":"true","spec.devEnvironments.defaultComponents":"true","spec.devEnvironments.defaultEditor":"true","spec.devEnvironments.disableContainerBuildCapabilities":"true"}'
  creationTimestamp: "2024-09-27T14:56:03Z"
  finalizers:
  - checluster.che.eclipse.org
  - cluster-resources.finalizers.che.eclipse.org
  - cheGateway.clusterpermissions.finalizers.che.eclipse.org
  - oauthclients.finalizers.che.eclipse.org
  - dashboard.clusterpermissions.finalizers.che.eclipse.org
  - container-build.finalizers.che.eclipse.org
  - consolelink.finalizers.che.eclipse.org
  generation: 7
  name: devspaces
  namespace: openshift-devspaces
  resourceVersion: "521000533"
  uid: afb74ebf-afec-4ce9-bdf9-dad91157b744
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    devWorkspace:
      runningLimit: "5"
    devfileRegistry: {}
    imagePuller:
      enable: true
      spec: {}
    metrics:
      enable: true
    pluginRegistry:
      deployment:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/georg-devspaces/che-plugin-registry
          name: plugin-registry
      openVSXURL: ""
  containerRegistry: {}
  devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    ignoredUnrecoverableEvents:
    - FailedScheduling
    maxNumberOfRunningWorkspacesPerUser: 5
    maxNumberOfWorkspacesPerUser: 5
    secondsOfInactivityBeforeIdling: -1
    secondsOfRunBeforeIdling: -1
    security: {}
    startTimeoutSeconds: 600
    storage:
      perWorkspaceStrategyPvcConfig:
        claimSize: 10Gi
      pvcStrategy: per-workspace
  gitServices: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
status:
  chePhase: Active
  cheURL: https://devspaces.apps.ocp.ocp-gm.de
  cheVersion: 3.20.0
  devfileRegistryURL: ""
  gatewayPhase: Established
  pluginRegistryURL: https://devspaces.apps.ocp.ocp-gm.de/plugin-registry/v3
  workspaceBaseDomain: apps.ocp.ocp-gm.de
